prometheus-nginx-exporter:
  enabled: true
  nginxServer: "http://auth-service-nginx.auth-service.svc.cluster.local/nginx_status"
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: 30s
    path: /metrics
    additionalLabels:
      release: prometheus